<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net48</TargetFramework>
		<RootNamespace>SpeedupThings</RootNamespace>
		<AssemblyName>SpeedupThings</AssemblyName>
		<Version>1.0.0</Version>
		<BepInExPluginGuid>kupie.gk2.speedupthings</BepInExPluginGuid>
		<BepInExPluginName>Speedup Things</BepInExPluginName>
	</PropertyGroup>

</Project>
