<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net48</TargetFramework>
		<RootNamespace>MoreInventorySlots</RootNamespace>
		<AssemblyName>MoreInventorySlots</AssemblyName>
		<Version>1.0.0</Version>
		<BepInExPluginGuid>kupie.gk2.moreinventoryslots</BepInExPluginGuid>
		<BepInExPluginName>More Inventory Slots</BepInExPluginName>
	</PropertyGroup>

</Project>
